spring:
  datasource:
    url: jdbc:mysql://47.98.143.6:3307/sunshixiong?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: ssx#1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: yuesao
      password: sunshixiong
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB